"""'Init'

Revision ID: c848befef7f6
Revises: ce8f237f9769
Create Date: 2024-03-02 18:07:15.262917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "c848befef7f6"
down_revision: Union[str, None] = "ce8f237f9769"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("crated_at", sa.DateTime(), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.alter_column(
        "contacts",
        "email",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlalchemy_utils.types.email.EmailType(length=255),
        existing_nullable=True,
    )
    op.create_foreign_key(
        None, "contacts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.alter_column(
        "contacts",
        "email",
        existing_type=sqlalchemy_utils.types.email.EmailType(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("contacts", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
